apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: devsec
          image: 192.168.6.99:8082/devsecops:latest
          ports:
            - containerPort: 9090


---

apiVersion: v1
kind: Service
metadata:
  name: prod-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30005
  externalIPs:
    - 192.168.6.99

